//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercedes_Matriz_de_Conhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadesDiario
    {
        public int IdFuncionario { get; set; }
        public int IdWorkzoneAtividade { get; set; }
        public int idAtividadeDiario { get; set; }
    
        public virtual tblFuncionarios tblFuncionarios { get; set; }
        public virtual tblWorkzoneXAtividades tblWorkzoneXAtividades { get; set; }
    }
}
