//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercedes_Matriz_de_Conhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoTeste
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateSaved { get; set; }
        public byte[] Arquivo { get; set; }
    }
}
