//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercedes_Matriz_de_Conhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFuncionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFuncionarios()
        {
            this.tblAvaliacaoFuncXworkzoneXatividade = new HashSet<tblAvaliacaoFuncXworkzoneXatividade>();
            this.tblAvaliacaoFuncXworkzoneXatividadeHist = new HashSet<tblAvaliacaoFuncXworkzoneXatividadeHist>();
            this.tblStatusFuncionarioXworkzoneXtreinamento = new HashSet<tblStatusFuncionarioXworkzoneXtreinamento>();
            this.tblWorkzoneXAtividades = new HashSet<tblWorkzoneXAtividades>();
        }
    
        public int idfuncionario { get; set; }
        public string RE { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
        public string JustificativaNaoAtivo { get; set; }
        public Nullable<int> idBu_atual { get; set; }
        public Nullable<int> idBu_Origem { get; set; }
        public Nullable<int> idWorkzone { get; set; }
        public string IdentificadorAuxiliar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAvaliacaoFuncXworkzoneXatividade> tblAvaliacaoFuncXworkzoneXatividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAvaliacaoFuncXworkzoneXatividadeHist> tblAvaliacaoFuncXworkzoneXatividadeHist { get; set; }
        public virtual tblWorkzone tblWorkzone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStatusFuncionarioXworkzoneXtreinamento> tblStatusFuncionarioXworkzoneXtreinamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkzoneXAtividades> tblWorkzoneXAtividades { get; set; }
    }
}
