//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercedes_Matriz_de_Conhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFuncionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFuncionarios()
        {
            this.tblMatrizFuncXAtividades = new HashSet<tblMatrizFuncXAtividades>();
            this.tblMatrizFuncXTreinamento = new HashSet<tblMatrizFuncXTreinamento>();
            this.tblWorkzoneXFuncionario = new HashSet<tblWorkzoneXFuncionario>();
        }
    
        public int idfuncionario { get; set; }
        public string RE { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
        public string JustificativaNaoAtivo { get; set; }
        public int idBu_Origem { get; set; }
        public string IdentificadorAuxiliar { get; set; }
        public int idAmericas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMatrizFuncXAtividades> tblMatrizFuncXAtividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMatrizFuncXTreinamento> tblMatrizFuncXTreinamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkzoneXFuncionario> tblWorkzoneXFuncionario { get; set; }
    }
}
