//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercedes_Matriz_de_Conhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatrizWorkzoneHistorico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMatrizWorkzoneHistorico()
        {
            this.tblMatrizFuncActivityHistorico = new HashSet<tblMatrizFuncActivityHistorico>();
            this.tblMatrizFuncTreinHistorico = new HashSet<tblMatrizFuncTreinHistorico>();
        }
    
        public int idMatrizHistorico { get; set; }
        public int idWorkzone { get; set; }
        public string nomeWorkzone { get; set; }
        public string BUWorkzone { get; set; }
        public string CCWorkzone { get; set; }
        public string LinhaWorkzone { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public string UsuarioCriacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMatrizFuncActivityHistorico> tblMatrizFuncActivityHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMatrizFuncTreinHistorico> tblMatrizFuncTreinHistorico { get; set; }
    }
}
