//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercedes_Matriz_de_Conhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatusFuncionarioXworkzoneXtreinamento
    {
        public int idFuncionario { get; set; }
        public int idTreinamento { get; set; }
        public int idPerfilItem { get; set; }
        public int idStatusTreinamento { get; set; }
        public int idWorkzone { get; set; }
    
        public virtual tblFuncionarios tblFuncionarios { get; set; }
        public virtual tblPerfilItem tblPerfilItem { get; set; }
        public virtual tblTreinamento tblTreinamento { get; set; }
        public virtual tblTreinamentoStatus tblTreinamentoStatus { get; set; }
        public virtual tblWorkzone tblWorkzone { get; set; }
    }
}
