//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercedes_Matriz_de_Conhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkzoneXAtividades
    {
        public int idWorkzoneAtividade { get; set; }
        public Nullable<int> idWorkzone { get; set; }
        public Nullable<int> idAtividade { get; set; }
        public Nullable<int> Ordem { get; set; }
    
        public virtual tblAtividades tblAtividades { get; set; }
        public virtual tblWorkzone tblWorkzone { get; set; }
    }
}
